### ISSUE TITLE
Cleanup | Nov 2020

### ISSUE THREAD

**Issue by sotrh** [sotrh/learn-wgpu#122]
Some things I need to work on

- [x] Come up with a method to handle swap chain `Outdated` errors, and discuss the other possible errors in the main tutorial. #121 
- [x] Use `mint` for all the `Vertex`/`ModelVertex` structs so we can use bytemuck derive #109
- [x] Switch to using vertex buffers for instancing #116 
- [x] Fix issues with `build.rs` #119 
- [x] Fix any issues with the texturing tutorial #120 
- [x] Finish compute example and put it in showcase

Stretch goals

- [x] imgui showcase #110

**Comment by sotrh** [comment]
I ended up not using mint and converted all the structs that would be copied to a buffer into raw `f32` arrays.

**Comment by kanerogers** [comment]
@sotrh If you're short on time I'd be happy to clean up the texturing tutorial a bit! 😄 The main thing seems to be the code you ended up using wraps the texture operations, but this wasn't elaborated on in the tutorial.

Wrapping up all the texture operations in one `mod` makes sense from a refactoring point of view but from the point of view of a reader following along, it'd probably be easier to just keep it all in the `State::new()` method.

Let me know what you think!

**Comment by sotrh** [comment]
@kanerogers That should be fine. The compute example might take a bit. It shouldn't conflict with the texture tutorial at all.

**Comment by kanerogers** [comment]
@sotrh Awesome. I've made my suggestions [here](https://github.com/sotrh/learn-wgpu/pull/124).
